name: CI/CD - Docker Build & Push

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
permissions:
  contents: write

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile


      - name: Run React tests
        run: echo "test pass for now .... "

      - name: Check latest commit message for Conventional Commit
        run: |
          set -e

          # Get latest commit message subject
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "Latest commit message: \"$COMMIT_MSG\""

          # Conventional commit regex
          REGEX="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\\([a-z0-9-]+\\))?: .+"

          # Skip merge commits
          if [[ "$COMMIT_MSG" =~ ^Merge\ [a-f0-9]{7,}\ into\ [a-f0-9]{7,}$ ]]; then
            echo "⚠️ Skipping merge commit."
            exit 0
          fi

          # Check the commit message
          if [[ ! "$COMMIT_MSG" =~ $REGEX ]]; then
            echo "::error ::❌ Non-conforming commit: \"$COMMIT_MSG\""
            exit 1
          else
            echo "✅ Commit is valid."
          fi


  docker-build-and-push:
    needs: test-and-validate
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Run Semantic Versioning
        id: version
        uses: ./.github/actions/version-bump

      - name: Create tag if not skipped
        if: steps.version.outputs.skip != 'true'
        run: |

          git tag ${{ steps.version.outputs.new_tag }}

          git remote set-url origin https://github.com/${{ github.repository }}
          git push origin ${{ steps.version.outputs.new_tag }}
      - name: Get short SHA
        id: vars
        run: echo "sha3=$(echo $GITHUB_SHA | cut -c1-3)" >> $GITHUB_OUTPUT

      - name: Set environment name
        id: envname
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=development" >> $GITHUB_OUTPUT
          fi

      - name: Applying Docker tags
        id: tags
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=prodv${{ steps.vars.outputs.sha3 }}" >> $GITHUB_OUTPUT
          else
            echo "tag=dev${{ steps.vars.outputs.sha3 }}" >> $GITHUB_OUTPUT
          fi

      - name: Print Environment
        run: echo "Using environment $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ steps.envname.outputs.env }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:${{ steps.tags.outputs.tag }}

