name: CI and CD for Frontend Code

on:
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - dev
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    # Checkout your code
    # defaults:
    #   run:
    #     working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Check Conventional Commits
      - name: Validate commit message
        run: chmod +x .github/scripts/check_commit.sh && .github/scripts/check_commit.sh
      # Install dependencies and cache it
      - name: setup-node
        uses:  actions/setup-node@v4
        with:
          node_version: 18
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

  create_semantic_docker_release:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-node
        uses: actions/setup-node@v4

        with:
          node_version: 18
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: npx semantic-release --branches dev

      - name: Create version Tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          NEW_BRANCH="v/${VERSION#v}"

          git config user.name="action-user"
          git congig user.email="action-user@github.com"
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"



  build_and_push_docker_image:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest version from tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          VERSION_NUMBER=${VERSION#v}
          echo "version=$VERSION_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-app:v${{ steps.version.outputs.version }}
            ${{secrets.DOCKER_HUB_USERNAME}}/frontend-app:latest
